# git add .
# git commit -m "Trigger CI/CD deploy"
# git push origin main


name: CI/CD for Streamlit Sentiment App

on:
  push:
    branches:
      - main  # Trigger on push to main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.9.19
        uses: actions/setup-python@v4
        with:
          python-version: "3.9.19"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint check with flake8
        run: |
          pip install flake8
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics || true

      - name: Run unit tests
        run: |
          pip install pytest
          pytest tests/

      - name: Deploy to Render
        run: |
          curl "$RENDER_DEPLOY_HOOK"
